--- 
server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 1800
  port: 8081
management:
  security:
    enabled: false
spring: 
  datasource: 
    password:
    url: "jdbc:mysql://localhost:3306/workout?useSSL=false"
    username: root
  jpa: 
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  queries:
    users-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?